## **Análisis preliminar**

In [1]:
# Tratamiento de datos
import pandas as pd
pd.set_option('display.max_columns', None)

import sys
sys.path.append('../')

# Cargar automáticamente los archivos src
%load_ext autoreload
%autoreload 2

#Funciones personalizadas
from src import sp_eda as se

In [2]:
df = pd.read_csv("../data/cuestionario_bruto.csv")

In [3]:
se.analisis_preliminar(df)

,P1,P2,P2.1,P3,P4,P5,P6,P7,P8.1,P8.2,P8.3,P9,P10,P11.1,P11.2,P11.3,P11.4,P11.5,P11.6,P11.7,P12,P13,P14.1,P14.2,P14.3,P14.4,P14.5,P14.6,P14.7,P15,P16,P17,P18,P19,P20,P21,P22,P23
163,2002,No,Sí,NaN,28,0,De nadie en particular,N.C.,8,8,7,No,Sí,De acuerdo,Totalmente en desacuerdo,Totalmente en desacuerdo,En desacuerdo,En desacuerdo,En desacuerdo,De acuerdo,40 o más años,Falta de estabilidad económica,7,7,7,7,7,7,7,"No, debería ser más",10,No,Totalmente de acuerdo,Católica no practicante,6,Estudiante,No tiene ingresos de ningún tipo,Estudios universitarios o equivalentes
79,1982,No,Sí,NaN,Cuánto antes,8,"Entorno laboral, Sociedad en general",NaN,2,1,Nada de acuerdo 0,Sí,Sí,Totalmente de acuerdo,Ni acuerdo ni desacuerdo,Ni acuerdo ni desacuerdo,Totalmente de acuerdo,Totalmente de acuerdo,De acuerdo,De acuerdo,40 o más años,"Precariedad laboral, Estudios, No tener pareja",7,7,7,7,7,7,7,"No, debería ser más",10,No,Totalmente de acuerdo,Católica practicante,7,Técnicos y profesionales científicos e intelec...,De 1.100 a 1.800,Estudios universitarios o equivalentes
59,2001,No,Sí,NaN,A partir de los 30 años,2,De nadie en particular,NaN,8,2,8,No,No,Totalmente en desacuerdo,Totalmente en desacuerdo,Totalmente en desacuerdo,Totalmente en desacuerdo,Totalmente de acuerdo,Totalmente en desacuerdo,Totalmente de acuerdo,40 o más años,"Estudios, Falta de estabilidad económica",7,7,7,7,7,7,7,"No, debería ser más",10,No,Totalmente de acuerdo,Atea (niega la existencia de Dios),2,Estudiante,No tiene ingresos de ningún tipo,Estudios universitarios o equivalentes
223,1971,Sí,NaN,33.0,NaN,0,De nadie en particular,Miedo,5,5,N.C.,No,Sí,Ni acuerdo ni desacuerdo,Totalmente en desacuerdo,Totalmente de acuerdo,Totalmente en desacuerdo,Totalmente de acuerdo,Totalmente en desacuerdo,En desacuerdo,40 o más años,"Precariedad laboral, Difícil emancipación, No ...",7,7,7,7,7,7,7,Sí,10,No,Totalmente de acuerdo,Católica no practicante,0,Trabajadores no cualificados,No tiene ingresos de ningún tipo,Educación secundaria obligatoria
221,1978,Sí,NaN,28.0,NaN,5,De nadie en particular,"Ansiedad, Depresión, Miedo, Culpa, Preocupación",Nada de acuerdo 0,9,9,No,Sí,Totalmente de acuerdo,En desacuerdo,En desacuerdo,En desacuerdo,Totalmente de acuerdo,Ni acuerdo ni desacuerdo,En desacuerdo,35-39 años,"Precariedad laboral, Falta de estabilidad econ...",4,7,4,3,4,3,7,Sí,10,No,Totalmente de acuerdo,Católica no practicante,0,"Trabajadores de servicios de restauración, per...",De 1.100 a 1.800,Educación secundaria obligatoria

------------------------------------------------------
DIMENSIONES
Nuestro conjunto de datos presenta un total de 233 filas y 38 columnas
--------------------------------------------------------
INFO
<class 'pandas.DataFrame'>
RangeIndex: 233 entries, 0 to 232
Data columns (total 38 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   P1      233 non-null    int64
 1   P2      233 non-null    str
 2   P2.1    100 non-null    str
 3   P3      137 non-null    float64
 4   P4      71 non-null     str
 5   P5      233 non-null    int64
 6   P6      232 non-null    str
 7   P7      147 non-null    str
 8   P8.1    233 non-null    str
 9   P8.2    233 non-null    str
 10  P8.3    233 non-null    str
 11  P9      233 non-null    str
 12  P10     233 non-null    str
 13  P11.1   233 non-null    str
 14  P11.2   233 non-null    str
 15  P11.3   233 non-null    str
 16  P11.4   233 non-null    str
 17  P11.5   233 non-null    str
 18  P11.6   233 non-null    str
 19  P11.7   233 non-null    str
 20  P12     233 non-null    str
 21  P13     233 non-null    str
 22  P14.1   233 non-null    int64
 23  P14.2   233 non-null    int64
 24  P14.3   233 non-null    int64
 25  P14.4   233 non-null    int64
 26  P14.5   233 non-null    int64
 27  P14.6   233 non-null    int64
 28  P14.7   233 non-null    int64
 29  P15     233 non-null    str
 30  P16     233 non-null    int64
 31  P17     233 non-null    str
 32  P18     233 non-null    str
 33  P19     233 non-null    str
 34  P20     233 non-null    int64
 35  P21     232 non-null    str
 36  P22     233 non-null    str
 37  P23     233 non-null    str
dtypes: float64(1), int64(11), str(26)
memory usage: 69.3 KB

None

--------------------------------------------------------
NULOS

P1        0.0
P2        0.0
P2.1     57.0
P3       41.0
P4       70.0
P5        0.0
P6        0.0
P7       37.0
P8.1      0.0
P8.2      0.0
P8.3      0.0
P9        0.0
P10       0.0
P11.1     0.0
P11.2     0.0
P11.3     0.0
P11.4     0.0
P11.5     0.0
P11.6     0.0
P11.7     0.0
P12       0.0
P13       0.0
P14.1     0.0
P14.2     0.0
P14.3     0.0
P14.4     0.0
P14.5     0.0
P14.6     0.0
P14.7     0.0
P15       0.0
P16       0.0
P17       0.0
P18       0.0
P19       0.0
P20       0.0
P21       0.0
P22       0.0
P23       0.0
dtype: float64

2

--------------------------------------------------------
DUPLICADOS
Hay 0 duplicados en el conjunto de datos
--------------------------------------------------------
FRECUENCIA CATEGÓRICAS
P2
Sí    137
No     96
Name: count, dtype: int64
----------------
P2.1
Sí      63
No      22
N.S.    14
N.C.     1
Name: count, dtype: int64
----------------
P4
30                                                                                                                                                     10
35                                                                                                                                                      5
En tener estabilidad económica                                                                                                                          5
28                                                                                                                                                      5
27                                                                                                                                                      4
31                                                                                                                                                      3
34                                                                                                                                                      2
N.S.                                                                                                                                                    2
33                                                                                                                                                      2
Antes de los 30                                                                                                                                         2
A partir de los 32                                                                                                                                      1
Cuando tenga trabajo y unos ingresos estables :)                                                                                                        1
30/35 si tengo estabilidad económica                                                                                                                    1
A los 29 con una buena estabilidad                                                                                                                      1
30-35                                                                                                                                                   1
Cuando tenga estabilidad económica o haya conseguido mis propósitos en cuanto a estudios y el ámbito laboral                                            1
Cuando tenga estabilidad en la vida, ya sea laboral, economica o pareja                                                                                 1
29 o 30                                                                                                                                                 1
No sabría decirte una edad concreta pero sí que me gustaría tenerlos cuando tenga una buena economía independiente y me parezca el momento correcto     1
Cuando tenga una vivienda y un trabajo estable                                                                                                          1
26                                                                                                                                                      1
31/32                                                                                                                                                   1
29                                                                                                                                                      1
A partir de los 30 años                                                                                                                                 1
Como Máximo a los 38                                                                                                                                    1
Alrededor de los 30                                                                                                                                     1
29-32                                                                                                                                                   1
Cuánto antes                                                                                                                                            1
26-30                                                                                                                                                   1
40                                                                                                                                                      1
30 con trabajo estable y estabilidad económica                                                                                                          1
38                                                                                                                                                      1
A partir de los 35                                                                                                                                      1
Antes de los 30 y estable económicamente                                                                                                                1
Ya no es posible                                                                                                                                        1
36                                                                                                                                                      1
25-27                                                                                                                                                   1
Antes de los 30-35 años                                                                                                                                 1
30 - 32                                                                                                                                                 1
28-30                                                                                                                                                   1
33-34                                                                                                                                                   1
Name: count, dtype: int64
----------------
P6
De nadie en particular                                                 100
Sociedad en general                                                     44
Familiares                                                              27
N.C.                                                                    15
De mí misma                                                              6
N.S.                                                                     5
Familiares, Sociedad en general                                          5
Amistades                                                                5
Familiares, Amistades, Sociedad en general                               4
Pareja                                                                   4
Sociedad en general, De nadie en particular                              3
Pareja, Sociedad en general                                              2
Familiares, Amistades                                                    2
Familiares, Pareja, Sociedad en general                                  1
Pareja, Amistades, Sociedad en general                                   1
Amistades, Sociedad en general                                           1
Familiares, Entorno laboral, Sociedad en general                         1
Pareja, Sociedad en general, De mí misma                                 1
Entorno laboral, Sociedad en general                                     1
Familiares, Pareja, Amistades, Entorno laboral, Sociedad en general      1
Familiares, Pareja, Amistades, Entorno laboral                           1
Entorno laboral                                                          1
Familiares, Pareja                                                       1
Name: count, dtype: int64
----------------
P7
Preocupación                                                26
Ansiedad, Depresión, Miedo, Culpa, Soledad, Preocupación    21
Ninguna                                                     10
Ansiedad, Miedo, Preocupación                                9
N.C.                                                         8
Ansiedad, Preocupación                                       8
Miedo, Culpa, Preocupación                                   7
Ansiedad, Miedo, Culpa, Preocupación                         7
Ansiedad, Depresión, Miedo, Culpa, Preocupación              6
Miedo, Preocupación                                          5
Ansiedad, Miedo, Culpa, Soledad, Preocupación                4
Ansiedad, Miedo, Soledad, Preocupación                       3
Miedo                                                        3
Culpa, Preocupación                                          2
Todas las descritas                                          2
Ansiedad, Depresión, Miedo, Soledad, Preocupación            2
Soledad, Preocupación                                        2
Miedo, Culpa, Soledad, Preocupación                          2
Ansiedad, Culpa, Preocupación                                2
Ansiedad, Miedo                                              2
Ansiedad                                                     2
Ansiedad, Depresión, Culpa, Preocupación                     1
Depresión                                                    1
Ansiedad, Miedo, Soledad                                     1
Depresión, Miedo, Preocupación                               1
Ansiedad, Culpa, Soledad, Preocupación                       1
Miedo, Soledad, Preocupación                                 1
Ansiedad, Miedo, Culpa, Ninguna                              1
Ansiedad, Depresión, Preocupación                            1
Ansiedad, Depresión                                          1
Ansiedad, Soledad, Preocupación                              1
Ansiedad, Depresión, Miedo, Preocupación                     1
Miedo, Preocupación,                                         1
Ansiedad, Soledad                                            1
Ansiedad, Depresión, Soledad, Preocupación                   1
Name: count, dtype: int64
----------------
P8.1
Nada de acuerdo 0           38
1                           35
Totalmente de acuerdo 10    33
2                           32
8                           23
7                           18
3                           16
5                           14
9                           12
6                            8
4                            4
Name: count, dtype: int64
----------------
P8.2
1                           50
2                           29
5                           28
Nada de acuerdo 0           26
3                           20
4                           17
7                           13
Totalmente de acuerdo 10    13
6                           12
8                           10
9                           10
N.C.                         5
Name: count, dtype: int64
----------------
P8.3
1                           38
Nada de acuerdo 0           37
2                           35
5                           21
Totalmente de acuerdo 10    19
6                           13
4                           13
3                           12
9                           11
7                           10
8                           10
N.S.                         8
N.C.                         6
Name: count, dtype: int64
----------------
P9
No      159
Sí       56
N.S.     14
N.C.      4
Name: count, dtype: int64
----------------
P10
Sí      122
No       92
N.S.     16
N.C.      3
Name: count, dtype: int64
----------------
P11.1
Ni acuerdo ni desacuerdo    84
Totalmente en desacuerdo    47
En desacuerdo               36
De acuerdo                  34
Totalmente de acuerdo       28
N.S.                         3
N.C.                         1
Name: count, dtype: int64
----------------
P11.2
Totalmente en desacuerdo    152
En desacuerdo                50
Ni acuerdo ni desacuerdo     16
De acuerdo                    7
Totalmente de acuerdo         5
N.C.                          2
N.S.                          1
Name: count, dtype: int64
----------------
P11.3
Totalmente en desacuerdo    168
En desacuerdo                27
Totalmente de acuerdo        18
Ni acuerdo ni desacuerdo     10
De acuerdo                    9
N.S.                          1
Name: count, dtype: int64
----------------
P11.4
Totalmente en desacuerdo    97
Ni acuerdo ni desacuerdo    61
En desacuerdo               44
Totalmente de acuerdo       16
De acuerdo                   8
N.S.                         5
N.C.                         2
Name: count, dtype: int64
----------------
P11.5
Totalmente de acuerdo       151
De acuerdo                   50
Ni acuerdo ni desacuerdo     16
Totalmente en desacuerdo      7
N.S.                          5
En desacuerdo                 4
Name: count, dtype: int64
----------------
P11.6
De acuerdo                  55
En desacuerdo               53
Ni acuerdo ni desacuerdo    48
Totalmente en desacuerdo    42
Totalmente de acuerdo       30
N.S.                         4
N.C.                         1
Name: count, dtype: int64
----------------
P11.7
Totalmente de acuerdo       86
De acuerdo                  41
Totalmente en desacuerdo    40
En desacuerdo               38
Ni acuerdo ni desacuerdo    19
N.C.                         7
N.S.                         2
Name: count, dtype: int64
----------------
P12
40 o más años    154
35-39 años        57
N.C.               8
N.S.               6
30-34 años         6
25-29 años         2
Name: count, dtype: int64
----------------
P13
Precariedad laboral, Difícil emancipación, Falta de estabilidad económica                                                                59
Precariedad laboral, Falta de estabilidad económica, Incertidumbre acerca del futuro                                                     26
Precariedad laboral, Difícil emancipación, Falta de estabilidad económica, Incertidumbre acerca del futuro                               20
Difícil emancipación, Falta de estabilidad económica, Incertidumbre acerca del futuro                                                    12
Precariedad laboral, Falta de estabilidad económica                                                                                      12
Precariedad laboral, Difícil emancipación, Estudios, Falta de estabilidad económica, Incertidumbre acerca del futuro                      9
Precariedad laboral, Estudios, Falta de estabilidad económica                                                                             8
Falta de estabilidad económica                                                                                                            8
Precariedad laboral, Falta de estabilidad económica, No tener pareja                                                                      7
Precariedad laboral, Difícil emancipación, Estudios, Falta de estabilidad económica, No tener pareja, Incertidumbre acerca del futuro     7
Difícil emancipación, Estudios, Falta de estabilidad económica                                                                            6
Difícil emancipación, Falta de estabilidad económica, No tener pareja                                                                     5
Precariedad laboral, Difícil emancipación, Estudios                                                                                       4
Precariedad laboral, Difícil emancipación, Estudios, Falta de estabilidad económica                                                       4
Precariedad laboral, Difícil emancipación, Falta de estabilidad económica, No tener pareja, Incertidumbre acerca del futuro               4
Precariedad laboral, Estudios, No tener pareja                                                                                            4
Estudios, Falta de estabilidad económica                                                                                                  4
Falta de estabilidad económica, No tener pareja, Incertidumbre acerca del futuro                                                          4
Difícil emancipación, Falta de estabilidad económica                                                                                      3
Precariedad laboral, Difícil emancipación, Estudios, Falta de estabilidad económica, No tener pareja                                      3
No tener pareja                                                                                                                           2
N.C.                                                                                                                                      2
Precariedad laboral, Estudios, Falta de estabilidad económica, Incertidumbre acerca del futuro                                            2
Estudios, Falta de estabilidad económica, No tener pareja                                                                                 2
Falta de estabilidad económica, No tener pareja                                                                                           2
Estudios, Falta de estabilidad económica, Incertidumbre acerca del futuro                                                                 1
Precariedad laboral, Difícil emancipación, Incertidumbre acerca del futuro                                                                1
Precariedad laboral, Estudios, N.S.                                                                                                       1
Falta de estabilidad económica, Incertidumbre acerca del futuro                                                                           1
Precariedad laboral, No tener pareja, Incertidumbre acerca del futuro                                                                     1
Estudios, Falta de estabilidad económica, No tener pareja, Incertidumbre acerca del futuro                                                1
Falta de estabilidad económica, Incertidumbre acerca del futuro, Compatibilidad laboral                                                   1
Difícil emancipación, Estudios, No tener pareja, La inestabilidad de las relaciones de pareja                                             1
Estudios, Falta de estabilidad económica, Viajar, ocio ect                                                                                1
Precariedad laboral, Difícil emancipación, No tener pareja, Incertidumbre acerca del futuro                                               1
Precariedad laboral, Difícil emancipación                                                                                                 1
Precariedad laboral, Difícil emancipación, No tener pareja                                                                                1
Falta de estabilidad económica, No tener pareja, Infertilidad                                                                             1
Incertidumbre acerca del futuro                                                                                                           1
Name: count, dtype: int64
----------------
P15
No, debería ser más                                     165
Sí                                                       33
Debería ser más para la mujer y menos para el hombre     22
N.S.                                                      7
N.C.                                                      4

       count         mean        std     min     25%     50%     75%     max
P1     233.0  1983.652361  14.559160  1950.0  1970.0  1987.0  1997.0  2020.0
P3     137.0    28.489051   5.834881     2.0    25.0    29.0    33.0    41.0
P5     233.0     2.695279   3.122061     0.0     0.0     1.0     5.0    10.0
P14.1  233.0     6.420601   0.997370     1.0     6.0     7.0     7.0     7.0
P14.2  233.0     6.527897   0.840947     2.0     6.0     7.0     7.0     7.0
P14.3  233.0     6.309013   1.078295     1.0     6.0     7.0     7.0     7.0
P14.4  233.0     6.068670   1.138854     1.0     5.0     6.0     7.0     7.0
P14.5  233.0     6.420601   1.018749     1.0     6.0     7.0     7.0     7.0
P14.6  233.0     5.982833   1.255902     1.0     5.0     6.0     7.0     7.0
P14.7  233.0     6.557940   0.898917     1.0     6.0     7.0     7.0     7.0
P16    233.0     8.738197   1.906240     0.0     8.0    10.0    10.0    10.0
P20    233.0     3.596567   2.374503     0.0     2.0     4.0     5.0    10.0

Imprimimos los resultados que sean igual a 2020 para ver cuántas respuestas hay

In [4]:
print((df['P1'] == 2020).sum())

# Habrá que eliminar esas dos respuestas

2